CREATE DATABASE reservation_hotel CHARACTER SET 'utf8';

CREATE TABLE hotel (
	id SMALLINT UNSIGNED  NOT NULL AUTO_INCREMENT,
	nom VARCHAR(10) NOT NULL,
	nb_rooms_available INT NOT NULL,
	
	PRIMARY KEY(id)
)ENGINE=INNODB;

CREATE TABLE chambre (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	hotel_id INT NOT NULL,
	room_number INT NOT NULL,
	date_min_av DATETIME NOT NULL,
	date_max_av DATETIME NOT NULL,
	
	PRIMARY KEY(id)
	FOREIGN KEY('hotel id') REFERENCES hotel(id)
)ENGINE=INNODB;

CREATE TABLE reservations (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,

)