CREATE DATABASE reservation_hotel CHARACTER SET 'utf8';

CREATE TABLE hotel (
	id SMALLINT UNSIGNED  NOT NULL AUTO_INCREMENT,
	nom VARCHAR(10) NOT NULL,
	nb_rooms INT NOT NULL,
	
	PRIMARY KEY(id)
)

ENGINE=INNODB;